### ISSUE TITLE
Supported environmental variables in logging configuration

### ISSUE THREAD

**Issue by wwonigkeit** [vorteil/vorteil#108]
### Summary

Support the ability to use the pre-defined vorteil environmental variables in the logging statements (or possibly throughout the configuration file). See the below configuration for logging to an ELK stack locally:

```
[[logging]]
  config = ["Name=tcp" , "Host=$EXT_IP0", "Port=10100", "Format=json", "tls=Off"]
  type = "system"

[[logging]]
  config = ["Name=tcp" , "Host=$EXT_IP0", "Port=10100", "Format=json", "tls=Off"]
  type = "kernel"
```

### Priority

High importance, but not critical

**Comment by jensg-st** [comment]
Environment variables can now be replaced with global environment vars and environment vars from cloud user data.
