### ISSUE TITLE
cli prints warning about wrong kernel versions

### ISSUE THREAD

**Issue by jensg-st** [vorteil/vorteil#114]
### Problem description

Tools are throwing a warning about an unusual kernel version. 

### Expected behaviour

No error message if the kernel has not changed

### Actual behaviour

Warning:

```detected an unusual remote kernel file update for source 'https://downloads.vorteil.io/kernels' on kernel '20.10.5'```

**Comment by alankm** [comment]
Resolved with 9d48d47c76768bbc105a1e80d5a5bf9fe18eb509
