### ISSUE TITLE
CNCF-Runtime discussion/presentation

### ISSUE THREAD

**Issue by raravena80** [vorteil/vorteil#118]
Hello Vorteil team,

I'm one of the co-chairs of the CNCF SIG-Runtime. I'm reaching out and I think it would be great for you to present/discuss the project at one of our meetings. For example, a general overview of the project or/and a demo.

Feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by jensg-st** [comment]
Hi,

thank you for contacting us. I will send you an email.

Thanks
