### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by Wolfsrudel** [vorteil/vorteil#120]
### Problem description

Just a little typo in the documentation. 

### Expected behaviour

Typo is gone. 

### Actual behaviour

At the documentation page
https://docs.vorteil.io/docs/guides/configure-machines/build-from-os/
at step 6 there is a `[[netowrk]]` instead of `[[network]]`

**Comment by jalfvort** [comment]
Thank you for spotting that typo. It has been fixed.

Related Commit: https://github.com/vorteil/vorteil.github.io/commit/eb489865470d773c23bc399ec3e151ea38f06324
