### ISSUE TITLE
Virtualizer, adding fail with Graphql error

### ISSUE THREAD

**Issue by wahmedswl** [vorteil/vorteil#129]
### Problem description

Not able to Virtualizer from Vorteil Studio, getting following error 
```
GraphQL ERROR: Syntax Error GraphQL request (1:109) Unterminated string. 1: mutation newHyperVVirtualizer { newHyperVVirtualizer(name:"HyperV", headless: true, switch: "Default Switch ^ 2: ") }
```

### Expected behaviour

Virtualization platform should be added.

### Actual behaviour

Getting graphql error and not able to add.

### Steps to reproduce

1. List of steps that must be taken to reproduce the issue.

### System details

Please include details about the system that the issue can be reproduced on, including:

- operating system / version ``````
- CLI version (`$ vorteil version`) ```client: 4.0.2-37d914d (26 Aug 20 00:04 +0000)
  api: 0.1.x
server: 4.0.2-37d914d (26 Aug 20 00:04 UTC)
  api: 0.1.1
  compiler: 3.0.0
    kernel: 1.0.x
    package: 3.x```
- hypervisors being used (firecracker, Virtualbox etc.) ```Hyper-V```
- cloud environment (if applicable)

![image](https://user-images.githubusercontent.com/15020561/108580608-08f74c00-734e-11eb-99b4-26293fea07ad.png)

**Comment by trentis** [comment]
Hi, thanks for the report!

If you visit the included GraphQL Playground at  http://localhost:7472/graphql in your web browser, you could try to run the raw mutation yourself. Does this affect the result at all?
```
mutation newHyperVVirtualizer { 
  newHyperVVirtualizer(name:"HyperV", headless: true, switch: "Default Switch ^ 2:") 
}
```

Unfortunately I was not able to reproduce your error, so I hope this helps. The Vorteil Studio is currently out of date and does not support the latest kernel. We recommend using our up-to-date Command Line Interface tools which you can get by visiting our GitHub project page and navigating to the 'Releases' page.

Using the CLI, you can run a Vorteil VM on HyperV as follows:
```
vorteil.exe run <RUNNABLE> --platform hyper-v
```
