### ISSUE TITLE
firecracker not starting if no memory is configured in vcfg

### ISSUE THREAD

**Issue by jensg-st** [vorteil/vorteil#85]
### Problem description

If there no memory is set in vcfg a VM with platform "firecracker" does not start with erro:

```
Error starting virtual machine: machine needs a nonzero amount of memory
```

### Expected behaviour

Setting default memory for the VM

### Steps to reproduce

Create vcfg without ram set. 

### System details

Please include details about the system that the issue can be reproduced on, including:

- Linux
- firecracker
- local

**Comment by trentis** [comment]
Closing as we merged it in
